name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
     - name: List available Xcode versions
       run: ls /Applications | grep Xcode

     # Runs a single command using the runners shell
     - name: Run a one-line script
       run: sudo xcode-select -switch /Applications/Xcode_13.3.1.app && /usr/bin/xcodebuild -version
     - name: Install Dependencies
       run: |
         cd RawgExpert
         pod install --repo-update
     # Runs a set of commands using the runners shell
     - name: Run a multi-line script
       run: |
          cd RawgExpert
          xcodebuild test -workspace ProjectSource.xcworkspace -scheme GameCenter2 -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=14.1"
